-- Auto-generated airport timezone data from AirportUTCReport.csv
-- 259 airports

CREATE TABLE IF NOT EXISTS public.airports (
  id bigserial PRIMARY KEY,
  iata text NOT NULL UNIQUE,
  icao text,
  airport_name text NOT NULL,
  country_code text,
  country_name text,
  utc_offset_hours numeric(4,2) NOT NULL,
  utc_offset_str text NOT NULL,
  dst_offset_hours numeric(4,2),
  dst_start text,
  dst_end text,
  iana_timezone text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS airports_iata_idx ON public.airports(iata);

-- RLS
ALTER TABLE public.airports ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS airports_select ON public.airports;
CREATE POLICY airports_select ON public.airports FOR SELECT TO authenticated USING (true);

-- Seed data
INSERT INTO public.airports (iata, icao, airport_name, country_code, country_name, utc_offset_hours, utc_offset_str, dst_offset_hours, dst_start, dst_end, iana_timezone)
VALUES
  ('ADA', 'LTAF', 'ADANA', 'LT', 'TURKEY', 2, '+02:00', 3, '3/29/2026', '10/25/2026', 'Europe/Istanbul'),
  ('ADL', 'YPAD', 'ADELAIDE INTL,SA', 'Y', 'AUSTRALIA', 9.5, '+09:30', 10.5, '10/4/2026', '4/5/2026', 'Australia/Sydney'),
  ('AKL', 'NZAA', 'AUCKLAND INTL', 'NZ', 'NEW ZEALAND', 12, '+12:00', 13, '9/27/2026', '4/5/2026', 'Pacific/Auckland'),
  ('ALA', 'UAAA', 'ALMATY', 'UA', 'KAZAKHSTAN', 5, '+05:00', NULL, NULL, NULL, 'Asia/Almaty'),
  ('AMD', 'VAAH', 'AHMEDABAD', 'V', 'INDIA', 5.5, '+05:30', NULL, NULL, NULL, 'Asia/Kolkata'),
  ('AMS', 'EHAM', 'AMSTERDAM,SCHIPHOL', 'EH', 'NETHERLANDS', 1, '+01:00', 2, '3/29/2026', '10/25/2026', 'Europe/Amsterdam'),
  ('ANC', 'PANC', 'STEVENS ANCHORAGE INTL,AK', 'K', 'UNITED STATES', -9, '-09:00', -8, '3/8/2026', '11/1/2026', 'America/Anchorage'),
  ('AOJ', 'RJSA', 'AOMORI', 'R', 'JAPAN', 9, '+09:00', NULL, NULL, NULL, 'Asia/Tokyo'),
  ('ASP', 'YBAS', 'Alice Springs Airport', 'Y', 'AUSTRALIA', 9.5, '+09:30', 10.5, '10/4/2026', '4/5/2026', 'Australia/Sydney'),
  ('ATH', 'LGAV', 'ATHENS, VENIZELOS INTL', 'LG', 'GREECE', 2, '+02:00', 3, '3/29/2026', '10/25/2026', 'Europe/Athens'),
  ('ATQ', 'VIAR', 'AMRITSAR', 'V', 'INDIA', 5.5, '+05:30', NULL, NULL, NULL, 'Asia/Kolkata'),
  ('AVV', 'YMAV', 'AVALON,VI', 'Y', 'AUSTRALIA', 10, '+10:00', 11, '10/4/2026', '4/5/2026', 'Australia/Sydney'),
  ('AZI', 'OMAD', 'ABU DHABI AL BATEEN', 'OM', 'UNITED ARAB EMIRATES', 4, '+04:00', NULL, NULL, NULL, 'Asia/Dubai'),
  ('BAV', NULL, 'BAOTOU', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('BAX', 'UNBB', 'Barnaul Gherman Titov', 'U', 'RUSSIAN FEDERATION', 7, '+07:00', NULL, NULL, NULL, 'Asia/Krasnoyarsk'),
  ('BFI', 'KBFI', 'SEATTLE,WA,BOEING FIELD  KING CO INTL', 'K', 'UNITED STATES', -8, '-08:00', -7, '3/8/2026', '11/1/2026', 'America/Los_Angeles'),
  ('BII', NULL, 'BIKINI ATOLL', 'MH', 'HONDURAS', -6, '-06:00', NULL, NULL, NULL, 'America/Chicago'),
  ('BKK', 'VTBS', 'BANGKOK INTL', 'VT', 'THAILAND', 7, '+07:00', NULL, NULL, NULL, 'Asia/Bangkok'),
  ('BLR', 'VOBL', 'BANGALORE', 'V', 'INDIA', 5.5, '+05:30', NULL, NULL, NULL, 'Asia/Kolkata'),
  ('BMV', 'VVBM', 'BUON MA THUOT', 'VV', 'VIETNAM', 7, '+07:00', NULL, NULL, NULL, 'Asia/Ho_Chi_Minh'),
  ('BNE', 'YBBN', 'BRISBANE INTL,QL', 'Y', 'AUSTRALIA', 10, '+10:00', NULL, NULL, NULL, 'Australia/Brisbane'),
  ('BOM', 'VABB', 'MUMBAI,CHHATRAPATI SHIVAJI INTL', 'V', 'INDIA', 5.5, '+05:30', NULL, NULL, NULL, 'Asia/Kolkata'),
  ('BQS', 'UHBB', 'BLAGOVESCHENSK,IGNATYEVO', 'U', 'RUSSIAN FEDERATION', 9, '+09:00', NULL, NULL, NULL, 'Asia/Yakutsk'),
  ('BTH', 'WIKB', 'Bandar Udara Internasional Hang Nadim', 'W', 'INDONESIA', 7, '+07:00', NULL, NULL, NULL, 'Asia/Jakarta'),
  ('BWA', 'VNBW', 'Gautam Buddha International Airport', 'V', 'INDIA', 5.5, '+05:30', NULL, NULL, NULL, 'Asia/Kolkata'),
  ('BWN', 'WBSB', 'BANDAR SERI BEGAWAN,BRUNEI INTL', 'WB', 'BRUNEI DARUSSALAM', 8, '+08:00', NULL, NULL, NULL, 'Asia/Brunei'),
  ('CAN', 'ZGGG', 'GUANGZHOU,BAIYUN', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('CBR', 'YSCB', 'CANBERRA,AC', 'Y', 'AUSTRALIA', 10, '+10:00', 11, '10/4/2026', '4/5/2026', 'Australia/Sydney'),
  ('CCU', 'VECC', 'KOLKATA,NETAJI SUBHASH CHANDRA BOSE IN', 'V', 'INDIA', 5.5, '+05:30', NULL, NULL, NULL, 'Asia/Kolkata'),
  ('CDG', 'LFPG', 'PARIS, CHARLES DE GAULLE', 'LF', 'FRANCE', 1, '+01:00', 2, '3/29/2026', '10/25/2026', 'Europe/Paris'),
  ('CEB', 'RPVM', 'MACTAN, CEBU INTL', 'RP', 'PHILIPPINES', 8, '+08:00', NULL, NULL, NULL, 'Asia/Manila'),
  ('CEI', 'VTCT', 'CHIANG RAI INTL', 'VT', 'THAILAND', 7, '+07:00', NULL, NULL, NULL, 'Asia/Bangkok'),
  ('CGK', 'WIII', 'JAKARTA,SOEKARNO  HATTA INTL', 'W', 'INDONESIA', 7, '+07:00', NULL, NULL, NULL, 'Asia/Jakarta'),
  ('CGO', 'ZHCC', 'ZHENGZHOU,XINZHENG', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('CGQ', 'ZYCC', 'CHANGCHUN,DAFANGSHEN', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('CIT', 'UAII', 'SHYMKENT', 'UA', 'KAZAKHSTAN', 6, '+06:00', NULL, NULL, NULL, 'Asia/Almaty'),
  ('CJJ', 'RKTU', 'CHEONGJU INTERNATIONAL', 'RK', 'KOREA S.(REP. OF)', 9, '+09:00', NULL, NULL, NULL, 'Asia/Seoul'),
  ('CJU', 'RKPC', 'JEJU INTL', 'RK', 'KOREA S.(REP. OF)', 9, '+09:00', NULL, NULL, NULL, 'Asia/Seoul'),
  ('CKG', 'ZUCK', 'CHONGQING,JIANGBEI', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('CMB', 'VCBI', 'COLOMBO,BANDARANAIKE INTL', 'VC', 'SRI LANKA', 5.5, '+05:30', NULL, NULL, NULL, 'Asia/Colombo'),
  ('CNX', 'VTCC', 'CHIANG MAI INTL', 'VT', 'THAILAND', 7, '+07:00', NULL, NULL, NULL, 'Asia/Bangkok'),
  ('COK', 'VOCI', 'COCHIN INTL', 'V', 'INDIA', 5.5, '+05:30', NULL, NULL, NULL, 'Asia/Kolkata'),
  ('CRK', 'RPLC', 'LUZON ISLAND', 'RP', 'PHILIPPINES', 8, '+08:00', NULL, NULL, NULL, 'Asia/Manila'),
  ('CRZ', 'UTAV', 'CHARDZHOU', 'UN', 'TURKMENISTAN', 5, '+05:00', NULL, NULL, NULL, 'Asia/Ashgabat'),
  ('CSX', 'ZGHA', 'CHANGSHA,HUANGHUA', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('CTS', 'RJCC', 'SAPPORO,NEW CHITOSE', 'R', 'JAPAN', 9, '+09:00', NULL, NULL, NULL, 'Asia/Tokyo'),
  ('CTU', 'ZUUU', 'CHENGDU,SHUANGLIU', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('CXR', 'VVCR', 'CAM RANH INTL', 'VV', 'VIETNAM', 7, '+07:00', NULL, NULL, NULL, 'Asia/Ho_Chi_Minh'),
  ('CXT', 'YCHT', 'CHARTERS TOWERS', 'Y', 'AUSTRALIA', 10, '+10:00', NULL, NULL, NULL, 'Australia/Brisbane'),
  ('CZX', 'ZSCG', 'CHANGZHOU', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('DAC', 'VGHS', 'DHAKA,ZIA INTL', 'VG', 'BANGLADESH', 6, '+06:00', NULL, NULL, NULL, 'Asia/Dhaka'),
  ('DAD', 'VVDN', 'DANANG INTL', 'VV', 'VIETNAM', 7, '+07:00', NULL, NULL, NULL, 'Asia/Ho_Chi_Minh'),
  ('DAT', 'ZBDT', 'DATONG YUNGANG', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('DEL', 'VIDP', 'DELHI, INDIRA GANDHI INTL', 'V', 'INDIA', 5.5, '+05:30', NULL, NULL, NULL, 'Asia/Kolkata'),
  ('DIN', 'VVDB', 'DIEN  BIEN  PHU', 'VV', 'VIETNAM', 7, '+07:00', NULL, NULL, NULL, 'Asia/Ho_Chi_Minh'),
  ('DLC', 'ZYTL', 'DALIAN,ZHOUSHUIZI', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('DLI', 'VVDL', 'LIEN KHUONG - DALAT', 'VV', 'VIETNAM', 7, '+07:00', NULL, NULL, NULL, 'Asia/Ho_Chi_Minh'),
  ('DLZ', 'ZMDZ', 'DALANZADGAD', 'ZM', 'MONGOLIA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Ulaanbaatar'),
  ('DME', 'UUDD', 'MOSCOW,DOMODEDOVO', 'U', 'RUSSIAN FEDERATION', 4, '+04:00', NULL, NULL, NULL, 'Europe/Samara'),
  ('DMK', 'VTBD', 'DON MUANG', 'VT', 'THAILAND', 7, '+07:00', NULL, NULL, NULL, 'Asia/Bangkok'),
  ('DOH', 'OTBD', 'DOHA INTL', 'OT', 'QATAR', 3, '+03:00', NULL, NULL, NULL, 'Asia/Qatar'),
  ('DPS', 'WADD', 'DEN PASAR,BALI INTL', 'W', 'INDONESIA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Makassar'),
  ('DRW', 'YPDN', 'DARWIN INTL,NT', 'Y', 'AUSTRALIA', 9.5, '+09:30', NULL, NULL, NULL, 'Australia/Darwin'),
  ('DSN', 'ZBDS', 'DONGSHENG', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('DVO', 'RPMD', 'DAVAO,BANGOY INTL', 'RP', 'PHILIPPINES', 8, '+08:00', NULL, NULL, NULL, 'Asia/Manila'),
  ('DWC', 'OMDW', 'AL MAKTOUM INTL', 'OM', 'UNITED ARAB EMIRATES', 4, '+04:00', NULL, NULL, NULL, 'Asia/Dubai'),
  ('DXB', 'OMDB', 'DUBAI INTL', 'OM', 'UNITED ARAB EMIRATES', 4, '+04:00', NULL, NULL, NULL, 'Asia/Dubai'),
  ('DYG', 'ZGDY', 'DAYONG', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('EDI', 'EGPH', 'EDINBURGH', 'EG', 'UNITED KINGDOM', 0, '+00:00', 1, '3/29/2026', '10/25/2026', 'Europe/London'),
  ('ENH', 'ZHES', 'Enshi Xujiaping Airport', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('FCO', 'LIRF', 'ROME,FIUMICINO', 'LI', 'ITALY', 1, '+01:00', 2, '3/29/2026', '10/25/2026', 'Europe/Rome'),
  ('FKS', 'RJSF', 'FUKUSHIMA', 'R', 'JAPAN', 9, '+09:00', NULL, NULL, NULL, 'Asia/Tokyo'),
  ('FOC', 'ZSFZ', 'FUZHOU,CHANGLE', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('FRU', 'UCFM', 'BISHKEK,MANAS', 'UY', 'KYRGYZSTAN', 6, '+06:00', 6, '3/29/2026', '10/25/2026', 'Asia/Bishkek'),
  ('FSZ', 'RJNS', 'SHIZUOKA', 'R', 'JAPAN', 9, '+09:00', NULL, NULL, NULL, 'Asia/Tokyo'),
  ('FUK', 'RJFF', 'FUKUOKA', 'R', 'JAPAN', 9, '+09:00', NULL, NULL, NULL, 'Asia/Tokyo'),
  ('GAY', 'VEGY', 'GAYA', 'V', 'INDIA', 5.5, '+05:30', NULL, NULL, NULL, 'Asia/Kolkata'),
  ('GMP', 'RKSS', 'SEOUL, GIMPO INTL', 'RK', 'KOREA S.(REP. OF)', 9, '+09:00', NULL, NULL, NULL, 'Asia/Seoul'),
  ('GYD', 'UBBB', 'BAKU INTL, HEYDAR ALIYEV', 'UB', 'AZERBAIJAN', 4, '+04:00', NULL, NULL, NULL, 'Asia/Baku'),
  ('GZT', 'LTAJ', 'GAZIANTEP,OGUZELI', 'LT', 'TURKEY', 2, '+02:00', 3, '3/29/2026', '10/25/2026', 'Europe/Istanbul'),
  ('HAK', 'ZJHK', 'HAIKOU,MEILAN', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('HAM', 'EDDH', 'HAMBURG', 'ED', 'GERMANY', 1, '+01:00', 2, '3/29/2026', '10/25/2026', 'Europe/Berlin'),
  ('HAN', 'VVNB', 'HANOI,NOIBAI INTL', 'VV', 'VIETNAM', 7, '+07:00', NULL, NULL, NULL, 'Asia/Ho_Chi_Minh'),
  ('HDY', 'VTSS', 'SONGKHLA,HAT YAI INTL', 'VT', 'THAILAND', 7, '+07:00', NULL, NULL, NULL, 'Asia/Bangkok'),
  ('HET', 'ZBHH', 'HOHHOT,BAITA', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('HFE', 'ZSOF', 'HEFEI,LUOGANG', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('HGH', 'ZSHC', 'HANGZHOU,XIAOSHAN', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('HHA', 'ZGHA', 'HUANGHUA', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('HIA', 'ZSSH', 'HUAI''AN LIANSHUI', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('HIJ', 'RJOA', 'HIROSHIMA', 'R', 'JAPAN', 9, '+09:00', NULL, NULL, NULL, 'Asia/Tokyo'),
  ('HKG', 'VHHH', 'HONG KONG INTL', 'VH', 'HONG KONG', 8, '+08:00', NULL, NULL, NULL, 'Asia/Hong_Kong'),
  ('HKT', 'VTSP', 'PHUKET INTL', 'VT', 'THAILAND', 7, '+07:00', NULL, NULL, NULL, 'Asia/Bangkok'),
  ('HND', 'RJTT', 'TOKYO (HANEDA) INTL', 'R', 'JAPAN', 9, '+09:00', NULL, NULL, NULL, 'Asia/Tokyo'),
  ('HPH', 'VVCI', 'CAT BI - HAI PHONG', 'VV', 'VIETNAM', 7, '+07:00', NULL, NULL, NULL, 'Asia/Ho_Chi_Minh'),
  ('HRB', 'ZYHB', 'HARBIN,TAIPING', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('HUI', 'VVPB', 'PHU BAI INT - HUE', 'VV', 'VIETNAM', 7, '+07:00', NULL, NULL, NULL, 'Asia/Ho_Chi_Minh'),
  ('HUN', 'RCYU', 'HUALIEN', 'RC', 'TAIWAN', 8, '+08:00', NULL, NULL, NULL, 'Asia/Taipei'),
  ('HYD', 'VOHS', 'RAJIV GANDHI INTL', 'V', 'INDIA', 5.5, '+05:30', NULL, NULL, NULL, 'Asia/Kolkata'),
  ('IAD', 'KIAD', 'WASHINGTON DULLES INTL,VA', 'K', 'UNITED STATES', -5, '-05:00', -4, '3/8/2026', '11/1/2026', 'America/New_York'),
  ('IBR', 'RJAH', 'OMITAMA IBARAKI', 'R', 'JAPAN', 9, '+09:00', NULL, NULL, NULL, 'Asia/Tokyo'),
  ('ICN', 'RKSI', 'SEOUL INCHEON, INCHEON INTL', 'RK', 'KOREA S.(REP. OF)', 9, '+09:00', NULL, NULL, NULL, 'Asia/Seoul'),
  ('IKT', 'UIII', 'Irkutsk International Airport', 'U', 'RUSSIAN FEDERATION', 4, '+04:00', NULL, NULL, NULL, 'Europe/Samara'),
  ('INC', 'ZLIC', 'YINCHUAN', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('IST', 'LTBA', 'ISTANBUL,ATATURK', 'LT', 'TURKEY', 2, '+02:00', 3, '3/29/2026', '10/25/2026', 'Europe/Istanbul'),
  ('JAI', 'VIJP', 'JAIPUR', 'V', 'INDIA', 5.5, '+05:30', NULL, NULL, NULL, 'Asia/Kolkata'),
  ('JFK', 'KJFK', 'NEW YORK,NY,KENNEDY INTL', 'K', 'UNITED STATES', -5, '-05:00', -4, '3/8/2026', '11/1/2026', 'America/New_York'),
  ('JHB', 'WMKJ', 'JOHOR BAHRU,SULTAN ISMAIL', 'WM', 'MALAYSIA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Kuala_Lumpur'),
  ('JJN', 'ZSQZ', 'JINJIANG', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('KBV', 'VTSG', 'KRABI', 'VT', 'THAILAND', 7, '+07:00', NULL, NULL, NULL, 'Asia/Bangkok'),
  ('KHH', 'RCKH', 'KAOHSIUNG INTL', 'RC', 'TAIWAN', 8, '+08:00', NULL, NULL, NULL, 'Asia/Taipei'),
  ('KHN', 'ZSCN', 'NANCHANG', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('KHV', 'UHHH', 'Khabarovsk Novy Airport', 'U', 'RUSSIAN FEDERATION', 10, '+10:00', NULL, NULL, NULL, 'Asia/Vladivostok'),
  ('KIJ', 'RJSN', 'NIIGATA', 'R', 'JAPAN', 9, '+09:00', NULL, NULL, NULL, 'Asia/Tokyo'),
  ('KIX', 'RJBB', 'OSAKA, KANSAI INTL', 'R', 'JAPAN', 9, '+09:00', NULL, NULL, NULL, 'Asia/Tokyo'),
  ('KJA', 'UNKL', 'KRASNOYARSK', 'U', 'RUSSIAN FEDERATION', 7, '+07:00', NULL, NULL, NULL, 'Asia/Krasnoyarsk'),
  ('KMG', 'ZPPP', 'KUNMING,WUJIABA', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('KMQ', 'RJNK', 'KOMATSU', 'R', 'JAPAN', 9, '+09:00', NULL, NULL, NULL, 'Asia/Tokyo'),
  ('KNH', 'RCBS', 'KINMEN', 'RC', 'TAIWAN', 8, '+08:00', NULL, NULL, NULL, 'Asia/Taipei'),
  ('KOJ', 'RJFK', 'KAGOSHIMA', 'R', 'JAPAN', 9, '+09:00', NULL, NULL, NULL, 'Asia/Tokyo'),
  ('KOS', 'VDSV', 'KOMPONG SOM', 'VD', 'CAMBODIA', 7, '+07:00', NULL, NULL, NULL, 'Asia/Phnom_Penh'),
  ('KTI', 'VDTI', 'Techo International Airport', 'VD', 'CAMBODIA', 7, '+07:00', NULL, NULL, NULL, 'Asia/Phnom_Penh'),
  ('KTW', 'EPKT', 'KATOWICE,PYRZOWICE', 'EP', 'POLAND', 1, '+01:00', 2, '3/29/2026', '10/25/2026', 'Europe/Warsaw'),
  ('KUF', 'UWWW', 'SAMARA,KURUMOCH', 'U', 'RUSSIAN FEDERATION', 3, '+03:00', NULL, NULL, NULL, 'Europe/Moscow'),
  ('KUL', 'WMKK', 'KUALA LUMPUR INTL SEPANG', 'WM', 'MALAYSIA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Kuala_Lumpur'),
  ('KUN', 'EYKA', 'KAUNAS INTL', 'EY', 'LITHUANIA', 2, '+02:00', 3, '3/29/2026', '10/25/2026', 'Europe/Vilnius'),
  ('KWE', 'ZUGY', 'GUIYANG', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('KWL', 'ZGKL', 'GUILIN,LIANGJIANG', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('KZN', 'UWKD', 'KAZAN', 'U', 'RUSSIAN FEDERATION', 3, '+03:00', NULL, NULL, NULL, 'Europe/Moscow'),
  ('LAO', 'RPLI', 'LAOAG INTL', 'RP', 'PHILIPPINES', 8, '+08:00', NULL, NULL, NULL, 'Asia/Manila'),
  ('LAX', 'KLAX', 'LOS ANGELES INTL,CA', 'K', 'UNITED STATES', -8, '-08:00', -7, '3/8/2026', '11/1/2026', 'America/Los_Angeles'),
  ('LBG', 'LFPB', 'PARIS,LE BOURGET', 'LF', 'FRANCE', 1, '+01:00', 2, '3/29/2026', '10/25/2026', 'Europe/Paris'),
  ('LGW', 'EGKK', 'LONDON, GATWICK', 'EG', 'UNITED KINGDOM', 0, '+00:00', 1, '3/29/2026', '10/25/2026', 'Europe/London'),
  ('LHR', 'EGLL', 'LONDON, HEATHROW', 'EG', 'UNITED KINGDOM', 0, '+00:00', 1, '3/29/2026', '10/25/2026', 'Europe/London'),
  ('LHW', 'ZLLL', 'LANZHOU ZONGCHUAN', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('LIG', 'LFBL', 'LIMOGES,BELLEGARDE', 'LF', 'FRANCE', 1, '+01:00', 2, '3/29/2026', '10/25/2026', 'Europe/Paris'),
  ('LJG', 'ZPLJ', 'Lijiang Sanyi International Airport', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('LKO', 'VILK', 'LUCKNOW', 'V', 'INDIA', 5.5, '+05:30', NULL, NULL, NULL, 'Asia/Kolkata'),
  ('LOP', 'WADL', 'LOMBOK INTERNATIONAL', 'W', 'INDONESIA', 7, '+07:00', NULL, NULL, NULL, 'Asia/Jakarta'),
  ('LTH', 'VVLT', 'LONG THANH INTERNATIONAL AIRPORT', 'VV', 'VIETNAM', 7, '+07:00', NULL, NULL, NULL, 'Asia/Ho_Chi_Minh'),
  ('LYI', 'ZSLY', 'LINYI SHUBULING', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('MAA', 'VOMM', 'CHENNAI INTL', 'V', 'INDIA', 5.5, '+05:30', NULL, NULL, NULL, 'Asia/Kolkata'),
  ('MAN', 'EGCC', 'MANCHESTER', 'EG', 'UNITED KINGDOM', 0, '+00:00', 1, '3/29/2026', '10/25/2026', 'Europe/London'),
  ('MEL', 'YMML', 'MELBOURNE TULLAMARINE INTL', 'Y', 'AUSTRALIA', 10, '+10:00', 11, '10/4/2026', '4/5/2026', 'Australia/Sydney'),
  ('MFM', 'VMMC', 'MACAU INTL', 'VM', 'MACAU', 8, '+08:00', NULL, NULL, NULL, 'Asia/Macau'),
  ('MIA', 'KMIA', 'MIAMI INTL,FL', 'K', 'UNITED STATES', -5, '-05:00', -4, '3/8/2026', '11/1/2026', 'America/New_York'),
  ('MNL', 'RPLL', 'MANILA,NINOY AQUINO INTL', 'RP', 'PHILIPPINES', 8, '+08:00', NULL, NULL, NULL, 'Asia/Manila'),
  ('MST', 'EHBK', 'MAASTRICHT  AACHEN', 'EH', 'NETHERLANDS', 1, '+01:00', 2, '3/29/2026', '10/25/2026', 'Europe/Amsterdam'),
  ('MWX', 'RKJB', 'MUAN INTERNATIONAL', 'RK', 'KOREA S.(REP. OF)', 9, '+09:00', NULL, NULL, NULL, 'Asia/Seoul'),
  ('MYJ', 'RJOM', 'MATSUYAMA', 'R', 'JAPAN', 9, '+09:00', NULL, NULL, NULL, 'Asia/Tokyo'),
  ('MZG', 'RCQC', 'MAKUNG AB', 'RC', 'TAIWAN', 8, '+08:00', NULL, NULL, NULL, 'Asia/Taipei'),
  ('NGB', 'ZSNB', 'NINGBO,LISHE', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('NGO', 'RJGG', 'NAGOYA, CHUBU CENTRAIR INTL', 'R', 'JAPAN', 9, '+09:00', NULL, NULL, NULL, 'Asia/Tokyo'),
  ('NKG', 'ZSNJ', 'NANJING,LUKOU', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('NNG', 'ZGNN', 'NANNING,WUXU', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('NOZ', NULL, 'NOVOKUZNETSK', 'U', 'RUSSIAN FEDERATION', 7, '+07:00', NULL, NULL, NULL, 'Asia/Krasnoyarsk'),
  ('NQZ', 'UACC', 'Nursultan Nazarbayev', 'UA', 'KAZAKHSTAN', 5, '+05:00', NULL, NULL, NULL, 'Asia/Almaty'),
  ('NRT', 'RJAA', 'NARITA INTL', 'R', 'JAPAN', 9, '+09:00', NULL, NULL, NULL, 'Asia/Tokyo'),
  ('NTG', 'ZSNT', 'NANTONG', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('OKA', 'ROAH', 'NAHA', 'R', 'JAPAN', 9, '+09:00', NULL, NULL, NULL, 'Asia/Tokyo'),
  ('OKJ', 'RJOB', 'OKAYAMA AIRPORT', 'R', 'JAPAN', 9, '+09:00', NULL, NULL, NULL, 'Asia/Tokyo'),
  ('ORY', 'LFPO', 'PARIS,ORLY', 'LF', 'FRANCE', 1, '+01:00', 2, '3/29/2026', '10/25/2026', 'Europe/Paris'),
  ('OVB', 'UNNT', 'NOVOSIBIRSK,TOLMACHEVO', 'U', 'RUSSIAN FEDERATION', 7, '+07:00', NULL, NULL, NULL, 'Asia/Krasnoyarsk'),
  ('PAC', 'MPMG', 'PANAMA CITY', 'MP', 'PANAMA', -5, '-05:00', NULL, NULL, NULL, 'America/New_York'),
  ('PBH', 'VQPR', 'PARO', 'VQ', 'BHUTAN', 6, '+06:00', NULL, NULL, NULL, 'Asia/Dhaka'),
  ('PEK', 'ZBAA', 'BEIJING CAPITAL', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('PEN', 'WMKP', 'PENANG INTL', 'WM', 'MALAYSIA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Kuala_Lumpur'),
  ('PER', 'YPPH', 'PERTH INTL,WA', 'Y', 'AUSTRALIA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('PKX', 'ZBAD', 'BEIJING DAXING', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('PLM', 'WIPP', 'PALEMBANG,SULTAN M BADARUDDIN II', 'W', 'INDONESIA', 7, '+07:00', NULL, NULL, NULL, 'Asia/Jakarta'),
  ('PNH', 'VDPP', 'PHNOM PENH,POCHENTONG INTL', 'VD', 'CAMBODIA', 7, '+07:00', NULL, NULL, NULL, 'Asia/Phnom_Penh'),
  ('PQC', 'VVPQ', 'PHUQUOC', 'VV', 'VIETNAM', 7, '+07:00', NULL, NULL, NULL, 'Asia/Ho_Chi_Minh'),
  ('PRG', 'LKPR', 'PRAGUE,RUZYNE', 'LK', 'CZECH REP', 1, '+01:00', 2, '3/29/2026', '10/25/2026', 'Europe/Paris'),
  ('PUS', 'RKPK', 'BUSAN, GIMHAE INTL', 'RK', 'KOREA S.(REP. OF)', 9, '+09:00', NULL, NULL, NULL, 'Asia/Seoul'),
  ('PVG', 'ZSPD', 'SHANGHAI,PUDONG', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('PXU', 'VVPK', 'PLEIKU', 'VV', 'VIETNAM', 7, '+07:00', NULL, NULL, NULL, 'Asia/Ho_Chi_Minh'),
  ('REP', 'VDSR', 'SIEM REAP, CAMBODIA,SIEM REAP', 'VD', 'CAMBODIA', 7, '+07:00', NULL, NULL, NULL, 'Asia/Phnom_Penh'),
  ('RGN', 'VYYY', 'YANGON INTL', 'VY', 'MYANMAR (BURMA)', 6.5, '+06:30', NULL, NULL, NULL, 'Asia/Yangon'),
  ('RMQ', 'RCMQ', 'TAICHUNG  INTL', 'RC', 'TAIWAN', 8, '+08:00', NULL, NULL, NULL, 'Asia/Taipei'),
  ('ROR', 'PTRO', 'BABELTHUAP I,BABELTHUAP  KOROR', 'PW', 'PALAU', 9, '+09:00', NULL, NULL, NULL, 'Asia/Tokyo'),
  ('SAI', 'VDSA', 'The new Siem Reap Airport', 'VD', 'CAMBODIA', 7, '+07:00', NULL, NULL, NULL, 'Asia/Phnom_Penh'),
  ('SAW', 'LTFJ', 'ISTANBUL, SABIHA GOKCEN', 'LT', 'TURKEY', 2, '+02:00', 3, '3/29/2026', '10/25/2026', 'Europe/Istanbul'),
  ('SDJ', 'RJSS', 'SENDAI', 'R', 'JAPAN', 9, '+09:00', NULL, NULL, NULL, 'Asia/Tokyo'),
  ('SFO', 'KSFO', 'SAN FRANCISCO INTL,CA', 'K', 'UNITED STATES', -8, '-08:00', -7, '3/8/2026', '11/1/2026', 'America/Los_Angeles'),
  ('SGM', NULL, 'SAN IGNACIO', 'MM', 'MEXICO', -6, '-06:00', -5, '4/5/2026', '10/25/2026', 'America/Chicago'),
  ('SGN', 'VVTS', 'TANSONNHAT - HOCHIMINH', 'VV', 'VIETNAM', 7, '+07:00', NULL, NULL, NULL, 'Asia/Ho_Chi_Minh'),
  ('SHE', 'ZYTX', 'SHENYANG,TAOXIAN', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('SHM', 'RJBD', 'NANKI  SHIRAHAMA', 'R', 'JAPAN', 9, '+09:00', NULL, NULL, NULL, 'Asia/Tokyo'),
  ('SIN', 'WSSS', 'SINGAPORE,CHANGI', 'WS', 'SINGAPORE', 8, '+08:00', NULL, NULL, NULL, 'Asia/Singapore'),
  ('SJW', 'ZBSJ', 'SHIJIAZHUANG,ZHENGDING', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('SNO', 'VTUI', 'SAKON NAKHON', 'VT', 'THAILAND', 7, '+07:00', NULL, NULL, NULL, 'Asia/Bangkok'),
  ('STN', 'EGSS', 'LONDON, STANSTED', 'EG', 'UNITED KINGDOM', 0, '+00:00', 1, '3/29/2026', '10/25/2026', 'Europe/London'),
  ('SUB', 'WRSJ', 'SURABAYA,JUANDA', 'W', 'INDONESIA', 7, '+07:00', NULL, NULL, NULL, 'Asia/Jakarta'),
  ('SVO', 'UUEE', 'MOSCOW,SHEREMETYEVO', 'U', 'RUSSIAN FEDERATION', 3, '+03:00', NULL, NULL, NULL, 'Europe/Moscow'),
  ('SVX', 'USSS', 'YEKATERINBURG,KOLTSOVO', 'U', 'RUSSIAN FEDERATION', 6, '+06:00', NULL, NULL, NULL, 'Asia/Dhaka'),
  ('SWA', 'ZGOW', 'SHANTOU', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('SWF', 'KSWF', 'NEWBURGH,NY,STEWART INTL', 'K', 'UNITED STATES', -5, '-05:00', -4, '3/8/2026', '11/1/2026', 'America/New_York'),
  ('SYD', 'YSSY', 'SYDNEY, KINGSFORD SMITH INTL', 'Y', 'AUSTRALIA', 10, '+10:00', 11, '10/4/2026', '4/5/2026', 'Australia/Sydney'),
  ('SYX', 'ZJSY', 'SANYA,PHOENIX INTL', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('SZB', 'WMSA', 'SUBANG SULTAN ABDUL AZIZ SHAH', 'WM', 'MALAYSIA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Kuala_Lumpur'),
  ('SZX', 'ZGSZ', 'SHENZHEN,HUANGTIAN', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('TAE', 'RKTN', 'DAEGU INTERNATIONAL', 'RK', 'KOREA S.(REP. OF)', 9, '+09:00', NULL, NULL, NULL, 'Asia/Seoul'),
  ('TAK', 'RJOT', 'TAKAMATSU AIRPORT', 'R', 'JAPAN', 9, '+09:00', NULL, NULL, NULL, 'Asia/Tokyo'),
  ('TAO', 'ZSQD', 'QINGDAO,LIUTING', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('TAS', 'UTTT', 'TASHKENT,YUZHNY', 'UT', 'UZBEKISTAN', 5, '+05:00', 5, '3/29/2026', '10/25/2026', 'Asia/Karachi'),
  ('TBB', 'VVTH', 'TUY HOA', 'VV', 'VIETNAM', 7, '+07:00', NULL, NULL, NULL, 'Asia/Ho_Chi_Minh'),
  ('TFU', 'ZUTF', 'CHENGDU TIANFU', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('THD', 'VVTX', 'SAO VANG - THO XUAN', 'VV', 'VIETNAM', 7, '+07:00', NULL, NULL, NULL, 'Asia/Ho_Chi_Minh'),
  ('TLS', 'LFBO', 'TOULOUSE,BLAGNAC', 'LF', 'FRANCE', 1, '+01:00', 2, '3/29/2026', '10/25/2026', 'Europe/Paris'),
  ('TLV', 'LLBG', 'TEL AVIV,BEN GURION', 'LL', 'ISRAEL', 2, '+02:00', 3, '3/27/2026', '10/4/2026', 'Europe/Istanbul'),
  ('TNA', 'ZSJN', 'JINAN,YAOQIANG', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('TNN', 'RCNN', 'TAINAN AERO', 'RC', 'TAIWAN', 8, '+08:00', NULL, NULL, NULL, 'Asia/Taipei'),
  ('TPE', 'RCTP', 'TAIPEI,TAOYUAN INTL', 'RC', 'TAIWAN', 8, '+08:00', NULL, NULL, NULL, 'Asia/Taipei'),
  ('TRZ', 'VOTR', 'TIRUCHIRAPPALLI', 'V', 'INDIA', 5.5, '+05:30', NULL, NULL, NULL, 'Asia/Kolkata'),
  ('TSE', 'UACC', 'AKMOLA, ASTANA', 'UA', 'KAZAKHSTAN', 6, '+06:00', NULL, NULL, NULL, 'Asia/Almaty'),
  ('TSK', NULL, 'TASKUL', 'AY', 'PAPUA NEW GUINEA', 10, '+10:00', NULL, NULL, NULL, 'Australia/Brisbane'),
  ('TSN', 'ZBTJ', 'TIANJIN,BINHAI', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('TTT', 'RCFN', 'TAITUNG AIRPORT', 'RC', 'TAIWAN', 8, '+08:00', NULL, NULL, NULL, 'Asia/Taipei'),
  ('TXN', 'ZSTX', 'HUANGSHAN TUNXI', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('TYN', 'ZBYN', 'TAIYUAN,WUSU', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('UBN', 'ZMCK', 'Chinggis Khaan International Airport', 'ZM', 'MONGOLIA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Ulaanbaatar'),
  ('UFA', 'UWUU', 'Ufa International Airport', 'U', 'RUSSIAN FEDERATION', 5, '+05:00', NULL, NULL, NULL, 'Asia/Yekaterinburg'),
  ('UIH', 'VVPC', 'PHU CAT - QUI NHON', 'VV', 'VIETNAM', 7, '+07:00', NULL, NULL, NULL, 'Asia/Ho_Chi_Minh'),
  ('UKB', 'RJBE', 'KOBE AIRPORT', 'R', 'JAPAN', 9, '+09:00', NULL, NULL, NULL, 'Asia/Tokyo'),
  ('ULN', 'ZMUB', 'ULAANBAATAR,BUYANT  UKHAA', 'ZM', 'MONGOLIA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Ulaanbaatar'),
  ('URC', 'ZWWW', 'Urumqi Diwopu International', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('UTP', 'VTBU', 'RAYONG,U  TAPHAO INTL', 'VT', 'THAILAND', 7, '+07:00', NULL, NULL, NULL, 'Asia/Bangkok'),
  ('UYN', 'ZLYL', 'YULIN', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('VCA', 'VVCT', 'CAN THO INTL', 'VV', 'VIETNAM', 7, '+07:00', NULL, NULL, NULL, 'Asia/Ho_Chi_Minh'),
  ('VCL', 'VVCA', 'CHU LAI', 'VV', 'VIETNAM', 7, '+07:00', NULL, NULL, NULL, 'Asia/Ho_Chi_Minh'),
  ('VCS', 'VVCS', 'CON DAO AIRPORT', 'VV', 'VIETNAM', 7, '+07:00', NULL, NULL, NULL, 'Asia/Ho_Chi_Minh'),
  ('VDH', 'VVDH', 'DONG HOI', 'VV', 'VIETNAM', 7, '+07:00', NULL, NULL, NULL, 'Asia/Ho_Chi_Minh'),
  ('VDO', 'VVVD', 'VAN DON INTL', 'VV', 'VIETNAM', 7, '+07:00', NULL, NULL, NULL, 'Asia/Ho_Chi_Minh'),
  ('VII', 'VVVH', 'VINH INTL', 'VV', 'VIETNAM', 7, '+07:00', NULL, NULL, NULL, 'Asia/Ho_Chi_Minh'),
  ('VKO', 'UUWW', 'MOSCOW,VNUKOVO', 'U', 'RUSSIAN FEDERATION', 4, '+04:00', NULL, NULL, NULL, 'Europe/Samara'),
  ('VNS', 'VEBN', 'VARANASI', 'V', 'INDIA', 5.5, '+05:30', NULL, NULL, NULL, 'Asia/Kolkata'),
  ('VTE', 'VLVT', 'VIENTIANE,WATTAY INTL', 'VL', 'LAOS (PEOP.DEM.REP.)', 7, '+07:00', NULL, NULL, NULL, 'Asia/Bangkok'),
  ('VVO', 'UHWW', 'VLADIVOSTOK,KNEVICHI', 'U', 'RUSSIAN FEDERATION', 10, '+10:00', NULL, NULL, NULL, 'Asia/Vladivostok'),
  ('WAW', 'EPWA', 'WARSAW,OKECIE', 'EP', 'POLAND', 1, '+01:00', 2, '3/29/2026', '10/25/2026', 'Europe/Warsaw'),
  ('WNZ', 'ZSWZ', 'WENZHOU', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('WUH', 'ZHHH', 'WUHAN,TIANHE', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('WUX', 'ZSWX', 'WUXI', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('XFN', 'ZHXF', 'XIANGYANG LIUJI AIRPORT', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('XFW', 'EDHI', 'HAMBURG,FINKENWERDER', 'ED', 'GERMANY', 1, '+01:00', 2, '3/29/2026', '10/25/2026', 'Europe/Berlin'),
  ('XIY', 'ZLXY', 'XIAN,XIANYANG', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('XMN', 'ZSAM', 'XIAMEN,GAOQI', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('XNN', 'ZLXN', 'Xining Caojiapu International Airport', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('XUZ', 'ZSXZ', 'XUZHOU', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('YCU', 'ZBYC', 'YUNCHENG YANHU', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('YGJ', 'RJOH', 'YONAGO,MIHO AERO', 'R', 'JAPAN', 9, '+09:00', NULL, NULL, NULL, 'Asia/Tokyo'),
  ('YIH', 'ZHYC', 'YICHANG', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('YIW', 'ZSYW', 'YIWU', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('YNT', 'ZSYT', 'YANTAI,LAISHAN', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('YNY', 'RKNY', 'YANGYANG INTL', 'RK', 'KOREA S.(REP. OF)', 9, '+09:00', NULL, NULL, NULL, 'Asia/Seoul'),
  ('YTY', 'ZSYA', 'YANGZHOU TAIZHOU', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('ZAG', 'LDZA', 'ZAGREB,PLESO', 'LD', 'CROATIA', 1, '+01:00', 2, '3/29/2026', '10/25/2026', 'Europe/Paris'),
  ('ZGC', 'ZLLL', 'LANZHOU ZHONGCHUAN', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('ZHA', 'ZGZJ', 'Zhanjiang Wuchuan International Airport', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai'),
  ('ZIA', 'UUBW', 'Zhukovsky International Airport', 'U', 'RUSSIAN FEDERATION', 4, '+04:00', NULL, NULL, NULL, 'Europe/Samara'),
  ('ZYI', 'ZUZY', 'ZUNYI', 'Z', 'CHINA', 8, '+08:00', NULL, NULL, NULL, 'Asia/Shanghai')
ON CONFLICT (iata) DO UPDATE SET
  icao = EXCLUDED.icao,
  airport_name = EXCLUDED.airport_name,
  utc_offset_hours = EXCLUDED.utc_offset_hours,
  utc_offset_str = EXCLUDED.utc_offset_str,
  dst_offset_hours = EXCLUDED.dst_offset_hours,
  dst_start = EXCLUDED.dst_start,
  dst_end = EXCLUDED.dst_end,
  iana_timezone = EXCLUDED.iana_timezone;
